/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsWorkflowAutomationRouteImport } from './routes/projects.workflow-automation'
import { Route as ProjectsTerminalPortfolioRouteImport } from './routes/projects.terminal-portfolio'
import { Route as ProjectsAnalyticsWorkbenchRouteImport } from './routes/projects.analytics-workbench'
import { Route as CareerStaffProductEngineerRouteImport } from './routes/career.staff-product-engineer'
import { Route as CareerSeniorFullstackEngineerRouteImport } from './routes/career.senior-fullstack-engineer'
import { Route as CareerFrontendEngineerRouteImport } from './routes/career.frontend-engineer'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsWorkflowAutomationRoute =
  ProjectsWorkflowAutomationRouteImport.update({
    id: '/workflow-automation',
    path: '/workflow-automation',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsTerminalPortfolioRoute =
  ProjectsTerminalPortfolioRouteImport.update({
    id: '/terminal-portfolio',
    path: '/terminal-portfolio',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsAnalyticsWorkbenchRoute =
  ProjectsAnalyticsWorkbenchRouteImport.update({
    id: '/analytics-workbench',
    path: '/analytics-workbench',
    getParentRoute: () => ProjectsRoute,
  } as any)
const CareerStaffProductEngineerRoute =
  CareerStaffProductEngineerRouteImport.update({
    id: '/staff-product-engineer',
    path: '/staff-product-engineer',
    getParentRoute: () => CareerRoute,
  } as any)
const CareerSeniorFullstackEngineerRoute =
  CareerSeniorFullstackEngineerRouteImport.update({
    id: '/senior-fullstack-engineer',
    path: '/senior-fullstack-engineer',
    getParentRoute: () => CareerRoute,
  } as any)
const CareerFrontendEngineerRoute = CareerFrontendEngineerRouteImport.update({
  id: '/frontend-engineer',
  path: '/frontend-engineer',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/frontend-engineer': typeof CareerFrontendEngineerRoute
  '/career/senior-fullstack-engineer': typeof CareerSeniorFullstackEngineerRoute
  '/career/staff-product-engineer': typeof CareerStaffProductEngineerRoute
  '/projects/analytics-workbench': typeof ProjectsAnalyticsWorkbenchRoute
  '/projects/terminal-portfolio': typeof ProjectsTerminalPortfolioRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/frontend-engineer': typeof CareerFrontendEngineerRoute
  '/career/senior-fullstack-engineer': typeof CareerSeniorFullstackEngineerRoute
  '/career/staff-product-engineer': typeof CareerStaffProductEngineerRoute
  '/projects/analytics-workbench': typeof ProjectsAnalyticsWorkbenchRoute
  '/projects/terminal-portfolio': typeof ProjectsTerminalPortfolioRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/frontend-engineer': typeof CareerFrontendEngineerRoute
  '/career/senior-fullstack-engineer': typeof CareerSeniorFullstackEngineerRoute
  '/career/staff-product-engineer': typeof CareerStaffProductEngineerRoute
  '/projects/analytics-workbench': typeof ProjectsAnalyticsWorkbenchRoute
  '/projects/terminal-portfolio': typeof ProjectsTerminalPortfolioRoute
  '/projects/workflow-automation': typeof ProjectsWorkflowAutomationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/frontend-engineer'
    | '/career/senior-fullstack-engineer'
    | '/career/staff-product-engineer'
    | '/projects/analytics-workbench'
    | '/projects/terminal-portfolio'
    | '/projects/workflow-automation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/frontend-engineer'
    | '/career/senior-fullstack-engineer'
    | '/career/staff-product-engineer'
    | '/projects/analytics-workbench'
    | '/projects/terminal-portfolio'
    | '/projects/workflow-automation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/frontend-engineer'
    | '/career/senior-fullstack-engineer'
    | '/career/staff-product-engineer'
    | '/projects/analytics-workbench'
    | '/projects/terminal-portfolio'
    | '/projects/workflow-automation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/workflow-automation': {
      id: '/projects/workflow-automation'
      path: '/workflow-automation'
      fullPath: '/projects/workflow-automation'
      preLoaderRoute: typeof ProjectsWorkflowAutomationRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/terminal-portfolio': {
      id: '/projects/terminal-portfolio'
      path: '/terminal-portfolio'
      fullPath: '/projects/terminal-portfolio'
      preLoaderRoute: typeof ProjectsTerminalPortfolioRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/analytics-workbench': {
      id: '/projects/analytics-workbench'
      path: '/analytics-workbench'
      fullPath: '/projects/analytics-workbench'
      preLoaderRoute: typeof ProjectsAnalyticsWorkbenchRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/career/staff-product-engineer': {
      id: '/career/staff-product-engineer'
      path: '/staff-product-engineer'
      fullPath: '/career/staff-product-engineer'
      preLoaderRoute: typeof CareerStaffProductEngineerRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/senior-fullstack-engineer': {
      id: '/career/senior-fullstack-engineer'
      path: '/senior-fullstack-engineer'
      fullPath: '/career/senior-fullstack-engineer'
      preLoaderRoute: typeof CareerSeniorFullstackEngineerRouteImport
      parentRoute: typeof CareerRoute
    }
    '/career/frontend-engineer': {
      id: '/career/frontend-engineer'
      path: '/frontend-engineer'
      fullPath: '/career/frontend-engineer'
      preLoaderRoute: typeof CareerFrontendEngineerRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerFrontendEngineerRoute: typeof CareerFrontendEngineerRoute
  CareerSeniorFullstackEngineerRoute: typeof CareerSeniorFullstackEngineerRoute
  CareerStaffProductEngineerRoute: typeof CareerStaffProductEngineerRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerFrontendEngineerRoute: CareerFrontendEngineerRoute,
  CareerSeniorFullstackEngineerRoute: CareerSeniorFullstackEngineerRoute,
  CareerStaffProductEngineerRoute: CareerStaffProductEngineerRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface ProjectsRouteChildren {
  ProjectsAnalyticsWorkbenchRoute: typeof ProjectsAnalyticsWorkbenchRoute
  ProjectsTerminalPortfolioRoute: typeof ProjectsTerminalPortfolioRoute
  ProjectsWorkflowAutomationRoute: typeof ProjectsWorkflowAutomationRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsAnalyticsWorkbenchRoute: ProjectsAnalyticsWorkbenchRoute,
  ProjectsTerminalPortfolioRoute: ProjectsTerminalPortfolioRoute,
  ProjectsWorkflowAutomationRoute: ProjectsWorkflowAutomationRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRouteWithChildren,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
