/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as SideProjectsRouteImport } from './routes/side-projects'
import { Route as HobbiesRouteImport } from './routes/hobbies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutMeRouteImport } from './routes/about-me'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkFrontendDeveloperHittahemRouteImport } from './routes/work.frontend-developer-hittahem'
import { Route as WorkCtoExtellioRouteImport } from './routes/work.cto-extellio'
import { Route as SideProjectsVbcRouteImport } from './routes/side-projects.vbc'
import { Route as SideProjectsOlEventsRouteImport } from './routes/side-projects.ol-events'
import { Route as SideProjectsElprIsRouteImport } from './routes/side-projects.elpr-is'
import { Route as SideProjectsCarlGrundbergsComRouteImport } from './routes/side-projects.carl-grundbergs-com'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const SideProjectsRoute = SideProjectsRouteImport.update({
  id: '/side-projects',
  path: '/side-projects',
  getParentRoute: () => rootRouteImport,
} as any)
const HobbiesRoute = HobbiesRouteImport.update({
  id: '/hobbies',
  path: '/hobbies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMeRoute = AboutMeRouteImport.update({
  id: '/about-me',
  path: '/about-me',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkFrontendDeveloperHittahemRoute =
  WorkFrontendDeveloperHittahemRouteImport.update({
    id: '/frontend-developer-hittahem',
    path: '/frontend-developer-hittahem',
    getParentRoute: () => WorkRoute,
  } as any)
const WorkCtoExtellioRoute = WorkCtoExtellioRouteImport.update({
  id: '/cto-extellio',
  path: '/cto-extellio',
  getParentRoute: () => WorkRoute,
} as any)
const SideProjectsVbcRoute = SideProjectsVbcRouteImport.update({
  id: '/vbc',
  path: '/vbc',
  getParentRoute: () => SideProjectsRoute,
} as any)
const SideProjectsOlEventsRoute = SideProjectsOlEventsRouteImport.update({
  id: '/ol-events',
  path: '/ol-events',
  getParentRoute: () => SideProjectsRoute,
} as any)
const SideProjectsElprIsRoute = SideProjectsElprIsRouteImport.update({
  id: '/elpr-is',
  path: '/elpr-is',
  getParentRoute: () => SideProjectsRoute,
} as any)
const SideProjectsCarlGrundbergsComRoute =
  SideProjectsCarlGrundbergsComRouteImport.update({
    id: '/carl-grundbergs-com',
    path: '/carl-grundbergs-com',
    getParentRoute: () => SideProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/hobbies': typeof HobbiesRoute
  '/side-projects': typeof SideProjectsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/side-projects/carl-grundbergs-com': typeof SideProjectsCarlGrundbergsComRoute
  '/side-projects/elpr-is': typeof SideProjectsElprIsRoute
  '/side-projects/ol-events': typeof SideProjectsOlEventsRoute
  '/side-projects/vbc': typeof SideProjectsVbcRoute
  '/work/cto-extellio': typeof WorkCtoExtellioRoute
  '/work/frontend-developer-hittahem': typeof WorkFrontendDeveloperHittahemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/hobbies': typeof HobbiesRoute
  '/side-projects': typeof SideProjectsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/side-projects/carl-grundbergs-com': typeof SideProjectsCarlGrundbergsComRoute
  '/side-projects/elpr-is': typeof SideProjectsElprIsRoute
  '/side-projects/ol-events': typeof SideProjectsOlEventsRoute
  '/side-projects/vbc': typeof SideProjectsVbcRoute
  '/work/cto-extellio': typeof WorkCtoExtellioRoute
  '/work/frontend-developer-hittahem': typeof WorkFrontendDeveloperHittahemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-me': typeof AboutMeRoute
  '/contact': typeof ContactRoute
  '/hobbies': typeof HobbiesRoute
  '/side-projects': typeof SideProjectsRouteWithChildren
  '/work': typeof WorkRouteWithChildren
  '/side-projects/carl-grundbergs-com': typeof SideProjectsCarlGrundbergsComRoute
  '/side-projects/elpr-is': typeof SideProjectsElprIsRoute
  '/side-projects/ol-events': typeof SideProjectsOlEventsRoute
  '/side-projects/vbc': typeof SideProjectsVbcRoute
  '/work/cto-extellio': typeof WorkCtoExtellioRoute
  '/work/frontend-developer-hittahem': typeof WorkFrontendDeveloperHittahemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-me'
    | '/contact'
    | '/hobbies'
    | '/side-projects'
    | '/work'
    | '/side-projects/carl-grundbergs-com'
    | '/side-projects/elpr-is'
    | '/side-projects/ol-events'
    | '/side-projects/vbc'
    | '/work/cto-extellio'
    | '/work/frontend-developer-hittahem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-me'
    | '/contact'
    | '/hobbies'
    | '/side-projects'
    | '/work'
    | '/side-projects/carl-grundbergs-com'
    | '/side-projects/elpr-is'
    | '/side-projects/ol-events'
    | '/side-projects/vbc'
    | '/work/cto-extellio'
    | '/work/frontend-developer-hittahem'
  id:
    | '__root__'
    | '/'
    | '/about-me'
    | '/contact'
    | '/hobbies'
    | '/side-projects'
    | '/work'
    | '/side-projects/carl-grundbergs-com'
    | '/side-projects/elpr-is'
    | '/side-projects/ol-events'
    | '/side-projects/vbc'
    | '/work/cto-extellio'
    | '/work/frontend-developer-hittahem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutMeRoute: typeof AboutMeRoute
  ContactRoute: typeof ContactRoute
  HobbiesRoute: typeof HobbiesRoute
  SideProjectsRoute: typeof SideProjectsRouteWithChildren
  WorkRoute: typeof WorkRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/side-projects': {
      id: '/side-projects'
      path: '/side-projects'
      fullPath: '/side-projects'
      preLoaderRoute: typeof SideProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hobbies': {
      id: '/hobbies'
      path: '/hobbies'
      fullPath: '/hobbies'
      preLoaderRoute: typeof HobbiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-me': {
      id: '/about-me'
      path: '/about-me'
      fullPath: '/about-me'
      preLoaderRoute: typeof AboutMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/frontend-developer-hittahem': {
      id: '/work/frontend-developer-hittahem'
      path: '/frontend-developer-hittahem'
      fullPath: '/work/frontend-developer-hittahem'
      preLoaderRoute: typeof WorkFrontendDeveloperHittahemRouteImport
      parentRoute: typeof WorkRoute
    }
    '/work/cto-extellio': {
      id: '/work/cto-extellio'
      path: '/cto-extellio'
      fullPath: '/work/cto-extellio'
      preLoaderRoute: typeof WorkCtoExtellioRouteImport
      parentRoute: typeof WorkRoute
    }
    '/side-projects/vbc': {
      id: '/side-projects/vbc'
      path: '/vbc'
      fullPath: '/side-projects/vbc'
      preLoaderRoute: typeof SideProjectsVbcRouteImport
      parentRoute: typeof SideProjectsRoute
    }
    '/side-projects/ol-events': {
      id: '/side-projects/ol-events'
      path: '/ol-events'
      fullPath: '/side-projects/ol-events'
      preLoaderRoute: typeof SideProjectsOlEventsRouteImport
      parentRoute: typeof SideProjectsRoute
    }
    '/side-projects/elpr-is': {
      id: '/side-projects/elpr-is'
      path: '/elpr-is'
      fullPath: '/side-projects/elpr-is'
      preLoaderRoute: typeof SideProjectsElprIsRouteImport
      parentRoute: typeof SideProjectsRoute
    }
    '/side-projects/carl-grundbergs-com': {
      id: '/side-projects/carl-grundbergs-com'
      path: '/carl-grundbergs-com'
      fullPath: '/side-projects/carl-grundbergs-com'
      preLoaderRoute: typeof SideProjectsCarlGrundbergsComRouteImport
      parentRoute: typeof SideProjectsRoute
    }
  }
}

interface SideProjectsRouteChildren {
  SideProjectsCarlGrundbergsComRoute: typeof SideProjectsCarlGrundbergsComRoute
  SideProjectsElprIsRoute: typeof SideProjectsElprIsRoute
  SideProjectsOlEventsRoute: typeof SideProjectsOlEventsRoute
  SideProjectsVbcRoute: typeof SideProjectsVbcRoute
}

const SideProjectsRouteChildren: SideProjectsRouteChildren = {
  SideProjectsCarlGrundbergsComRoute: SideProjectsCarlGrundbergsComRoute,
  SideProjectsElprIsRoute: SideProjectsElprIsRoute,
  SideProjectsOlEventsRoute: SideProjectsOlEventsRoute,
  SideProjectsVbcRoute: SideProjectsVbcRoute,
}

const SideProjectsRouteWithChildren = SideProjectsRoute._addFileChildren(
  SideProjectsRouteChildren,
)

interface WorkRouteChildren {
  WorkCtoExtellioRoute: typeof WorkCtoExtellioRoute
  WorkFrontendDeveloperHittahemRoute: typeof WorkFrontendDeveloperHittahemRoute
}

const WorkRouteChildren: WorkRouteChildren = {
  WorkCtoExtellioRoute: WorkCtoExtellioRoute,
  WorkFrontendDeveloperHittahemRoute: WorkFrontendDeveloperHittahemRoute,
}

const WorkRouteWithChildren = WorkRoute._addFileChildren(WorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutMeRoute: AboutMeRoute,
  ContactRoute: ContactRoute,
  HobbiesRoute: HobbiesRoute,
  SideProjectsRoute: SideProjectsRouteWithChildren,
  WorkRoute: WorkRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
