/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareerRouteImport } from './routes/career'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectRouteImport } from './routes/projects.$project'
import { Route as CareerEntryRouteImport } from './routes/career.$entry'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerRoute = CareerRouteImport.update({
  id: '/career',
  path: '/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => ProjectsRoute,
} as any)
const CareerEntryRoute = CareerEntryRouteImport.update({
  id: '/$entry',
  path: '/$entry',
  getParentRoute: () => CareerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/$entry': typeof CareerEntryRoute
  '/projects/$project': typeof ProjectsProjectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/$entry': typeof CareerEntryRoute
  '/projects/$project': typeof ProjectsProjectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/career': typeof CareerRouteWithChildren
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/career/$entry': typeof CareerEntryRoute
  '/projects/$project': typeof ProjectsProjectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/$entry'
    | '/projects/$project'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/$entry'
    | '/projects/$project'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/career'
    | '/contact'
    | '/projects'
    | '/career/$entry'
    | '/projects/$project'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareerRoute: typeof CareerRouteWithChildren
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career': {
      id: '/career'
      path: '/career'
      fullPath: '/career'
      preLoaderRoute: typeof CareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/career/$entry': {
      id: '/career/$entry'
      path: '/$entry'
      fullPath: '/career/$entry'
      preLoaderRoute: typeof CareerEntryRouteImport
      parentRoute: typeof CareerRoute
    }
  }
}

interface CareerRouteChildren {
  CareerEntryRoute: typeof CareerEntryRoute
}

const CareerRouteChildren: CareerRouteChildren = {
  CareerEntryRoute: CareerEntryRoute,
}

const CareerRouteWithChildren =
  CareerRoute._addFileChildren(CareerRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectRoute: typeof ProjectsProjectRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectRoute: ProjectsProjectRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareerRoute: CareerRouteWithChildren,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
